---
extends: [airbnb, plugin:flowtype/recommended]
env:
  node: true
  es6: true
  browser: true
globals:
  require: true
  config: true
  __DEV__: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins: [react, flowtype]

rules:
  max-len: [1, 140, 2, {"ignoreUrls":true}]
  comma-dangle: [error, never]
  no-console: [error, allow: [warn, error, info]]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  react/forbid-prop-types: 0
  arrow-parens: 0
  no-use-before-define: 0
  react/prefer-stateless-function: 1
  react/sort-comp: 1
  react/prop-types: 0
  import/prefer-default-export: 0
settings:
  import/resolver:
    babel-module: {}
    node:
      extensions:
        - .js
        - .jsx

      moduleDirectory:
        - node_modules
        - app
  settings:
    flowtype:
      onlyFilesWithFlowAnnotation: true
