---
extends: airbnb
env:
  node: true
  es6: true
  browser: true
globals:
  require: true
  config: true
  __DEV__: true
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins: [react]

rules:
  max-len: [1, 140, 2, {"ignoreUrls":true}]
  comma-dangle: [error, never]
  no-console: [error, allow: [warn, error, info]]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  react/forbid-prop-types: 0
settings:
  import/resolver:
    babel-module: {}
    node:
      extensions:
        - .js
        - .jsx

      moduleDirectory:
        - node_modules
        - app
